name: 'Octopulls - AI Code Review'
author: 'Imerso'
description: 'Action that automatically reviews your code with AI'
branding:
  color: white
  icon: git-merge
inputs:
  token:
    description: 'Token to access the GitHub API'
    required: true
  open-api-key:
    description: 'API key to access the OpenAI API'
    required: false
  pull-request-number:
    description: 'Number pull request'
    required: false
runs:
  using: 'node20'
  main: 'build/index.js'